services:
  mongo_DB:
    container_name: mongo_DB_valentines
    image: mongo:7.0
    network_mode: host
    networks:
      - DB_network
    ports:
      - 27017:27017
    volumes:
      - ${PWD}/data/mongo_db_data:/data/db  
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}

  tg_bot:
    build:
      context: ./
      dockerfile: Dockerfile.py
      network: host
    image: valentines
    container_name: tg_bot_valentines
    network_mode: host
    networks:
      - DB_network
    ports:
      - 79:8888
    volumes:
      - ${PWD}/data/logs:/usr/src/app/data/logs
    command: bash
    tty: true
    stdin_open: true

networks:
  DB_network:
    driver: bridge

volumes:
  mongodata:

    driver: local